server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.64.130:3306/guli_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: zhang123
  redis:
    host: 192.168.64.130
mybatis-plus:
  mapper-locations: classpath:mapper/ums/*.xml
  global-config:
    db-config:
      id-type: auto
